services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_db:



# services:
#   app:
#     build:
#       context: .
#     image: nextjs-dev
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=development
#     develop:
#       watch:
#         - action: sync
#           path: ./app
#           target: /app/app
#           ignore: 
#             - node_modules/
#         - action: rebuild
#           path: package.json